name: mad201_assignment01
description: Travel destinations Flutter app demonstrating OOP, multi-screen UI, navigation and state management.

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5

flutter:
  uses-material-design: true
  assets:
    - assets/images/profile.jpg
    - assets/images/destination1.jpg
    - assets/images/destination2.jpg
    # Add more image assets here
